# Local stack settings.
version: "2.1"
services:
  # Adds a Solr container with version 3.x of Solr - see
  #  http://docksal.readthedocs.io/en/master/tools/apache-solr/ and
  #  https://hub.docker.com/r/docksal/solr/tags/.
  # The "ports" and "environment" configuration allows the Solr server to be interacted
  #  directly with at http://192.168.64.100:8983/solr/
  solr:
    hostname: solr
    image: docksal/solr:1.0-solr3
    ports:
      - "8983:8983"
    environment:
      - DOMAIN_NAME=solr.${VIRTUAL_HOST}
  cli:
    image: docksal/cli:edge-php7
    environment:
      # PROFILE_NAME: "${PROFILE_NAME}"
      # SITE_NAME: "${SITE_NAME}"
      - PANTHEON_SITE_ENV
  mail:
    hostname: mail
    image: mailhog/mailhog
    expose:
      - "80"
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    labels:
      - io.docksal.virtual-host=webmail.${VIRTUAL_HOST}
    user: root
